M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date Чт 09 мар 2023 11:24:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-09T11:24:50+06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X53.17Y-74.75
X61.15Y-74.75
T2
X69.64Y-74.24
X82.34Y-74.24
T0
M30
